# Generated by Django 4.0.3 on 2022-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='isStaff',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userext',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userext',
            name='rolls',
            field=models.IntegerField(null=True),
        ),
    ]
