# Generated by Django 4.0.3 on 2022-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_system', '0002_order_dateoforder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='hall',
            field=models.IntegerField(null=True),
        ),
    ]
