# Generated by Django 4.0.3 on 2022-03-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_system', '0002_userext_isstaff_userext_phone_userext_rolls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userext',
            old_name='rolls',
            new_name='roll',
        ),
    ]
