# Generated by Django 4.0.3 on 2022-04-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_system', '0004_order_delived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delived',
            new_name='deli',
        ),
    ]
