# Generated by Django 4.0.3 on 2022-04-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_system', '0005_rename_delived_order_deli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
